"use client";

import { useMemo, useState } from "react";
import { BookOpenText, CircleCheck, FileText, MoreHorizontal, Plus, Search, Trash2, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import type { KnowledgeDocument } from "@/lib/domain/types";

export function KnowledgeWorkspace({ initialDocuments }: { initialDocuments: KnowledgeDocument[] }) {
  const [documents, setDocuments] = useState(initialDocuments); const [query, setQuery] = useState(""); const [editing, setEditing] = useState<KnowledgeDocument|null>(null); const [adding, setAdding] = useState(false);
  const visible = useMemo(()=>documents.filter((doc)=>`${doc.name} ${doc.type}`.toLowerCase().includes(query.toLowerCase())),[documents,query]);
  const save = async (document: KnowledgeDocument) => {
    setDocuments((items)=>items.some((item)=>item.id===document.id)?items.map((item)=>item.id===document.id?document:item):[document,...items]); setAdding(false); setEditing(null);
    try { await fetch("/api/knowledge",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(document)}); } catch { /* Local demo state remains explicit and usable. */ }
  };
  const remove = async (id:string) => { if(!window.confirm("Remove this knowledge document? Nova will no longer be able to use it."))return; setDocuments((items)=>items.filter((item)=>item.id!==id)); try { await fetch(`/api/knowledge?id=${encodeURIComponent(id)}`,{method:"DELETE"}); } catch {} };
  return <><div className="mt-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><label className="relative w-full max-w-md"><span className="sr-only">Search knowledge</span><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--muted)]"/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search documents" className="h-10 w-full rounded-md border border-[var(--line)] bg-[var(--surface-strong)] pl-9 pr-3 text-xs outline-none focus:border-[var(--signal)]"/></label><Button onClick={()=>setAdding(true)}><Plus size={14}/>Add document</Button></div>
    <section data-avatar-target="knowledge-library" className="surface mt-5 overflow-hidden"><header className="grid grid-cols-[1fr_auto] border-b border-[var(--line)] px-5 py-4"><div><p className="eyebrow">Knowledge sources</p><h2 className="mt-1 text-sm font-semibold">{documents.length} documents · {documents.reduce((sum,d)=>sum+d.words,0).toLocaleString("en-GB")} words</h2></div><BookOpenText size={18} className="text-[var(--signal)]"/></header><div className="divide-y divide-[var(--line)]">{visible.map((document)=><article key={document.id} data-avatar-target={`knowledge-${document.id}`} className="grid gap-4 p-5 hover:bg-[var(--canvas)] sm:grid-cols-[36px_minmax(0,1fr)_auto] sm:items-center"><div className="grid size-9 place-items-center rounded bg-[var(--signal-soft)] text-[var(--signal)]"><FileText size={16}/></div><button onClick={()=>setEditing(document)} className="min-w-0 text-left"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate text-sm font-semibold">{document.name}</h3><Badge tone={document.status==="READY"?"success":document.status==="FAILED"?"danger":"warning"}>{document.status}</Badge></div><p className="mt-1 text-[11px] text-[var(--muted)]">{document.type} · {document.words.toLocaleString()} words · Updated {new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short"}).format(new Date(document.updatedAt))}</p></button><div className="flex items-center gap-1"><button onClick={()=>setEditing(document)} className="rounded p-2 text-[var(--muted)] hover:bg-[var(--surface-strong)]" aria-label={`Edit ${document.name}`}><MoreHorizontal size={16}/></button><button onClick={()=>void remove(document.id)} className="rounded p-2 text-[var(--muted)] hover:bg-red-50 hover:text-[var(--danger)] dark:hover:bg-red-950" aria-label={`Remove ${document.name}`}><Trash2 size={15}/></button></div></article>)}{visible.length===0&&<div className="grid min-h-48 place-items-center text-sm text-[var(--muted)]">No matching knowledge sources.</div>}</div></section>
    <aside className="mt-4 flex max-w-2xl items-start gap-2.5 px-1 text-[11px] leading-5 text-[var(--muted)]"><CircleCheck size={15} strokeWidth={1.8} className="mt-0.5 shrink-0 text-[var(--signal)]" aria-hidden="true"/><p><span className="font-medium text-[var(--ink)]">Ready documents can be searched by Nova.</span> Upload plain-text or Markdown files.</p></aside>
    {(adding||editing)&&<DocumentDialog document={editing} onClose={()=>{setAdding(false);setEditing(null);}} onSave={save}/>}</>;
}

function DocumentDialog({document,onClose,onSave}:{document:KnowledgeDocument|null;onClose:()=>void;onSave:(document:KnowledgeDocument)=>void}) {
  const [name,setName]=useState(document?.name??""); const [type,setType]=useState(document?.type??"Company FAQ"); const [content,setContent]=useState(document?.content??"");
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/30 p-4" onMouseDown={(e)=>{if(e.currentTarget===e.target)onClose();}}><form onSubmit={(e)=>{e.preventDefault();onSave({id:document?.id??`kb-${crypto.randomUUID()}`,name,type,status:document?.status??"PROCESSING",words:content.trim().split(/\s+/).filter(Boolean).length,updatedAt:new Date().toISOString().slice(0,10),content});}} className="w-full max-w-xl bg-[var(--surface-strong)] shadow-2xl"><header className="flex items-center justify-between border-b border-[var(--line)] px-6 py-5"><div><p className="eyebrow">Knowledge source</p><h2 className="mt-1 text-lg font-semibold">{document?"Edit document":"Add document"}</h2></div><button type="button" onClick={onClose} className="rounded p-2 text-[var(--muted)]"><X size={18}/></button></header><div className="space-y-5 p-6"><label className="block text-xs font-semibold">Name<input required value={name} onChange={(e)=>setName(e.target.value)} className="mt-2 h-10 w-full rounded-md border border-[var(--line)] bg-[var(--canvas)] px-3 text-sm outline-none focus:border-[var(--signal)]"/></label><label className="block text-xs font-semibold">Document type<select value={type} onChange={(e)=>setType(e.target.value)} className="mt-2 h-10 w-full rounded-md border border-[var(--line)] bg-[var(--canvas)] px-3 text-sm"><option>Company FAQ</option><option>HR policy</option><option>Onboarding guide</option><option>Support procedure</option><option>Product documentation</option><option>Engineering guide</option></select></label><label className="block text-xs font-semibold">Content<textarea required rows={8} value={content} onChange={(e)=>setContent(e.target.value)} placeholder="Paste plain text or Markdown…" className="mt-2 w-full rounded-md border border-[var(--line)] bg-[var(--canvas)] p-3 text-sm leading-6 outline-none focus:border-[var(--signal)]"/></label><p className="text-[10px] text-[var(--muted)]">{content.trim().split(/\s+/).filter(Boolean).length} words · This content becomes available to Nova after processing.</p></div><footer className="flex justify-end gap-3 border-t border-[var(--line)] px-6 py-4"><Button type="button" variant="ghost" onClick={onClose}>Cancel</Button><Button type="submit">Save document</Button></footer></form></div>;
}
