"use client";

import { AlertTriangle, ArrowDownRight, ArrowUpRight, Download } from "lucide-react";
import { useRouter } from "next/navigation";
import { RevenueChart } from "@/components/charts/revenue-chart";
import { Metric } from "@/components/dashboard/metric";
import { Button } from "@/components/ui/button";
import { compareRevenue, findRevenueAnomalies, formatCurrency, revenueToCsv } from "@/lib/data/revenue";
import { useAvatarApp } from "@/components/avatar/avatar-provider";
import type { RevenuePoint } from "@/lib/domain/types";

export function RevenueDashboard({ initialPeriod, revenueData }: { initialPeriod: 7 | 30 | 90; revenueData: RevenuePoint[] }) {
  const app = useAvatarApp(); const router=useRouter();
  const period = initialPeriod; const data = revenueData.slice(-period); const summary = compareRevenue(revenueData, period); const anomalies = findRevenueAnomalies(revenueData, period); const largestRefund = [...data].sort((a,b)=>b.refunds-a.refunds)[0];
  const switchPeriod = (days: 7|30|90) => { app.setRevenuePeriod(days); router.replace(`/dashboard/revenue?period=${days}`); };
  const exportCsv = () => {
    const blob=new Blob(["\uFEFF",revenueToCsv(data)],{type:"text/csv;charset=utf-8"});
    const url=URL.createObjectURL(blob); const anchor=document.createElement("a");
    anchor.href=url; anchor.download=`nova-revenue-${period}-days.csv`; document.body.appendChild(anchor); anchor.click(); anchor.remove(); URL.revokeObjectURL(url);
  };
  return <>
    <div className="mt-6 flex flex-wrap items-center justify-between gap-3"><div className="flex border border-[var(--line)] bg-[var(--surface-strong)] p-1" aria-label="Revenue period">{([7,30,90] as const).map((days)=><button key={days} onClick={()=>switchPeriod(days)} className={`rounded px-4 py-2 text-xs font-semibold ${period===days?"bg-[var(--ink)] text-[var(--surface)]":"text-[var(--muted)] hover:text-[var(--ink)]"}`}>{days} days</button>)}</div><Button variant="secondary" size="sm" onClick={exportCsv}><Download size={14}/>Export CSV</Button></div>
    <section data-avatar-target="revenue-summary" className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label={`${period}-day net`} value={formatCurrency(summary.revenue)} detail={`${summary.percentageChange>=0?"+":""}${summary.percentageChange}% vs prior period`} signal={summary.percentageChange>=0?"up":"down"}/><Metric label="Previous period" value={formatCurrency(summary.previousPeriodRevenue)} detail={`${period} comparable days`}/><Metric label="Gross revenue" value={formatCurrency(summary.gross)} detail="Before refunds"/><Metric label="Refunds" value={formatCurrency(summary.refunds)} detail={`${((summary.refunds/summary.gross)*100).toFixed(1)}% of gross`} signal="down"/></section>
    <section data-avatar-target="revenue-chart" className="surface mt-6 p-5"><div className="mb-5 flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><p className="eyebrow">Daily movement</p><h2 className="mt-2 text-lg font-semibold">Net revenue</h2></div><div className="flex items-center gap-5 text-[10px] text-[var(--muted)]"><span className="flex items-center gap-2"><span className="size-2 bg-[var(--signal)]"/>Net daily revenue</span><span>All values GBP</span></div></div><RevenueChart data={data}/></section>
    <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_1.25fr]"><section data-avatar-target="refund-list" className="surface"><div className="border-b border-[var(--line)] p-5"><p className="eyebrow">Exceptions</p><h2 className="mt-2 text-base font-semibold">Refunds & anomalies</h2></div>{anomalies.length===0?<p className="p-5 text-sm text-[var(--muted)]">No material anomalies in this period.</p>:<div className="divide-y divide-[var(--line)]">{anomalies.map((item,index)=><article key={item.date} data-avatar-target={index===0?"largest-refund":undefined} className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">{new Intl.DateTimeFormat("en-GB",{weekday:"short",day:"numeric",month:"short"}).format(new Date(item.date))}</p><p className="mt-1 text-xs text-[var(--muted)]">{item.likelyCause}</p></div><span className="flex items-center gap-1 text-xs font-semibold text-[var(--danger)]"><ArrowDownRight size={13}/>{item.variancePercent}%</span></div><div className="mt-4 grid grid-cols-2 gap-4"><div><p className="eyebrow">Net</p><p className="mt-1 font-data text-sm">{formatCurrency(item.net)}</p></div><div><p className="eyebrow">Refunded</p><p className="mt-1 font-data text-sm text-[var(--danger)]">{formatCurrency(item.refunds)}</p></div></div>{item.date===largestRefund.date&&<p className="mt-4 flex items-start gap-2 border-t border-[var(--line)] pt-3 text-[11px] leading-5 text-[var(--muted)]"><AlertTriangle size={13} className="mt-0.5 shrink-0 text-[var(--warning)]"/>Enterprise annual plan cancelled during cooling-off period.</p>}</article>)}</div>}</section>
      <section data-avatar-target="daily-breakdown" className="surface overflow-hidden"><div className="flex items-center justify-between border-b border-[var(--line)] p-5"><div><p className="eyebrow">Ledger view</p><h2 className="mt-2 text-base font-semibold">Daily breakdown</h2></div><span className="text-[10px] text-[var(--muted)]">Latest 10 days</span></div><div className="overflow-x-auto"><table className="w-full min-w-[480px] text-left text-xs"><thead className="border-b border-[var(--line)] bg-[var(--canvas)] text-[10px] uppercase tracking-[.08em] text-[var(--muted)]"><tr><th className="px-5 py-3 font-medium">Date</th><th className="px-3 py-3 text-right font-medium">Gross</th><th className="px-3 py-3 text-right font-medium">Refunds</th><th className="px-5 py-3 text-right font-medium">Net</th></tr></thead><tbody className="divide-y divide-[var(--line)]">{[...data].reverse().slice(0,10).map((item)=><tr key={item.date} className="hover:bg-[var(--canvas)]"><td className="px-5 py-3">{new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short"}).format(new Date(item.date))}</td><td className="px-3 py-3 text-right font-data">{formatCurrency(item.gross)}</td><td className={`px-3 py-3 text-right font-data ${item.refunds?"text-[var(--danger)]":"text-[var(--muted)]"}`}>{item.refunds?`−${formatCurrency(item.refunds)}`:"—"}</td><td className="px-5 py-3 text-right font-data font-semibold">{formatCurrency(item.net)}</td></tr>)}</tbody></table></div><div className="flex items-center justify-between border-t border-[var(--line)] p-4 text-[11px] text-[var(--muted)]"><span>Compared with preceding {period} days</span><span className={`flex items-center gap-1 ${summary.percentageChange>=0?"text-[var(--signal)]":"text-[var(--danger)]"}`}>{summary.percentageChange>=0?<ArrowUpRight size={13}/>:<ArrowDownRight size={13}/>} {Math.abs(summary.percentageChange)}%</span></div></section></div>
  </>;
}
