import Link from "next/link";
import { ArrowRight, BarChart3, Box, Keyboard, Mic2, ShieldCheck, Wrench } from "lucide-react";
import { BrowserAvatarStage } from "@/components/avatar/browser-avatar-stage";
import { Mark } from "@/components/brand/mark";

const capabilities=[
  {icon:BarChart3,title:"Dashboard data stays in view",text:"Open the relevant revenue, refund, support, or knowledge view for each request."},
  {icon:Mic2,title:"Voice is optional",text:"Use browser speech where available, with typed commands in every session."},
  {icon:Wrench,title:"Actions stay explicit",text:"Navigate, filter, focus charts, and change settings through a defined set of interface controls."},
];

function AvatarPreview(){
  return <div className="relative min-h-[520px] overflow-hidden bg-[#142629] text-white lg:min-h-[620px]" aria-label="Nova avatar preview">
    <div className="absolute inset-x-0 top-0 z-10 flex items-center justify-between border-b border-white/10 px-5 py-4"><span className="font-data text-[10px] uppercase tracking-[.16em] text-white/55">Local 3D preview</span><span className="flex items-center gap-2 text-xs text-[#79d5cd]"><span className="status-dot"/> Available</span></div>
    <BrowserAvatarStage status="Listening"/>
    <div className="absolute inset-x-5 bottom-5 border border-white/12 bg-[#101d1f]/90 p-4 backdrop-blur-sm"><div className="mb-4 flex items-center justify-between"><div><p className="text-sm font-semibold">Nova</p><p className="mt-1 text-xs text-white/50">Browser-rendered controls</p></div><div className="flex h-6 items-center gap-1" aria-hidden="true">{[.4,.8,.55,1,.65,.35].map((scale,index)=><span key={index} className="wave-bar block h-5 w-[2px] bg-[#79d5cd]" style={{animationDelay:`${index*80}ms`,transform:`scaleY(${scale})`}}/>)}</div></div><p className="max-w-sm text-sm leading-6 text-white/78">“Opened the 90-day revenue view and highlighted the trend.”</p></div>
  </div>;
}

export default function Home(){
  return <main className="bg-[var(--surface)]">
    <header className="mx-auto flex h-20 max-w-[1440px] items-center justify-between border-x border-[var(--line)] px-6 lg:px-10"><Mark/><nav className="flex items-center gap-2"><Link href="/sign-in" className="px-4 py-2 text-sm text-[var(--muted)] hover:text-[var(--ink)]">Sign in</Link><Link href="/dashboard" className="inline-flex h-10 items-center gap-2 rounded-md bg-[var(--ink)] px-4 text-sm font-medium text-[var(--surface)]">Open dashboard <ArrowRight size={15}/></Link></nav></header>
    <section className="mx-auto grid max-w-[1440px] border border-[var(--line)] lg:grid-cols-[1.05fr_.95fr]">
      <div className="flex min-h-[620px] flex-col justify-between p-7 sm:p-12 lg:min-h-[720px] lg:p-16"><div><p className="eyebrow">Northstar operations</p><h1 className="mt-8 max-w-3xl text-[clamp(3.5rem,7.4vw,7.2rem)] font-medium leading-[.88] tracking-[-.065em]">Revenue, support, and knowledge.<br/><span className="text-[var(--signal)]">One working view.</span></h1></div><div className="mt-16 max-w-xl"><p className="text-lg leading-8 text-[var(--muted)]">Nova adds voice and text controls to the dashboard. The 3D interface runs in your browser and does not require a paid avatar provider.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/dashboard" className="inline-flex h-12 items-center gap-3 rounded-md bg-[var(--ink)] px-5 text-sm font-semibold text-[var(--surface)]">Open workspace <ArrowRight size={16}/></Link><Link href="#capabilities" className="inline-flex h-12 items-center rounded-md border border-[var(--line-strong)] px-5 text-sm font-semibold">View controls</Link></div><p className="mt-5 flex items-center gap-2 text-xs text-[var(--muted)]"><ShieldCheck size={14}/> No model download, camera upload, or avatar usage fee.</p></div></div>
      <AvatarPreview/>
    </section>
    <section id="capabilities" className="mx-auto max-w-[1440px] border-x border-b border-[var(--line)] px-7 py-20 sm:px-12 lg:px-16 lg:py-28"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Available controls</p><h2 className="mt-5 max-w-md text-4xl font-medium tracking-[-.045em] sm:text-5xl">Open a report, filter a queue, or review a source.</h2></div><div className="divide-y divide-[var(--line)] border-y border-[var(--line)]">{capabilities.map((item)=><article key={item.title} className="grid gap-5 py-7 sm:grid-cols-[48px_1fr] sm:items-start"><item.icon className="text-[var(--signal)]" size={22}/><div><h3 className="text-lg font-semibold">{item.title}</h3><p className="mt-2 max-w-xl leading-7 text-[var(--muted)]">{item.text}</p></div></article>)}</div></div></section>
    <section className="mx-auto grid max-w-[1440px] border-x border-b border-[var(--line)] lg:grid-cols-3"><div className="p-8 lg:p-12"><Box className="text-[var(--signal)]"/><h3 className="mt-10 text-xl font-semibold">Small local renderer</h3><p className="mt-3 leading-7 text-[var(--muted)]">The avatar is built from compact geometric primitives. There is no character model or large checkpoint to store.</p></div><div className="border-y border-[var(--line)] p-8 lg:border-x lg:border-y-0 lg:p-12"><Wrench className="text-[var(--signal)]"/><h3 className="mt-10 text-xl font-semibold">Defined actions</h3><p className="mt-3 leading-7 text-[var(--muted)]">Dashboard actions are explicit. Nova does not receive arbitrary code, SQL, or shell access.</p></div><div className="p-8 lg:p-12"><Keyboard className="text-[var(--signal)]"/><h3 className="mt-10 text-xl font-semibold">Typed fallback</h3><p className="mt-3 leading-7 text-[var(--muted)]">Typed requests provide the same navigation and filtering controls when speech recognition is unavailable.</p></div></section>
    <section className="mx-auto max-w-[1440px] border-x border-b border-[var(--line)] bg-[#172629] px-7 py-20 text-white sm:px-12 lg:flex lg:items-end lg:justify-between lg:px-16"><div><p className="font-data text-[10px] uppercase tracking-[.18em] text-[#79d5cd]">Northstar workspace</p><h2 className="mt-5 max-w-3xl text-5xl font-medium tracking-[-.05em] sm:text-7xl">Open the current operating view.</h2></div><Link href="/dashboard" className="mt-10 inline-flex h-12 items-center gap-3 rounded-md bg-[#d9ece8] px-5 text-sm font-semibold text-[#172629] lg:mt-0">Open workspace <ArrowRight size={16}/></Link></section>
    <footer className="mx-auto flex max-w-[1440px] items-center justify-between border-x border-[var(--line)] px-6 py-8 text-xs text-[var(--muted)]"><Mark/><span>Procedural 3D · Browser native · No usage fees</span></footer>
  </main>;
}
